name: gcr.io/cf-build-service-public

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'run action reason'
        required: false
        type: string
        default: 'manually test'
  schedule:
    - cron: '* 8 * * *'
  push:
      branches:
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  cf-build-service-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v3
        with:
          repository: x-mirrors/gcr.io
          ref: 'cf-build-service-public'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@v1
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/gcr.io/cf-build-service-public.txt"
          DEST_REPO: "docker.io/gcriocloudbuilders"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xactions"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"

      - name: Public result to github
        uses: x-actions/git-push@v1
        continue-on-error: true
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: 'cf-build-service-public'
          PUBLISH_DIR: 'gcr.io'
