name: infra-tools

on:
  schedule:
    - cron: '* 16 * * *'
  push:
      branches:
        - main

jobs:
  infra-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v2
        with:
          repository: x-mirrors/gcr.io
          ref: 'infra-tools'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@main
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/infra-tools.txt"
          DEST_REPO: "docker.io/k8sgcrioschedulerplugins"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xiexianbin"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"

      - name: Public result to github
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: infra-tools
          PUBLISH_DIR: 'gcr.io'
