name: registry.k8s.io/all-repos

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'run action reason'
        required: false
        type: string
        default: 'manually test'
  schedule:
    - cron: '* */3 * * *'
  push:
    branches:
      - main
      - dev
      - bug/**
      - fix/**
      - bugfix/**
      - feature/**
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  registry-k8s-io:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v3
        with:
          repository: x-mirrors/gcr.io
          ref: 'registry.k8s.io'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@feature/registry.k8s.io
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/${{ github.ref_name }}/registry.k8s.io/all-repos.txt"
          DEST_REPO: "docker.io/registryk8s"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xregistry"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"
          LOG_LEVEL: "DEBUG"
          AFTER_TIMEUPLOADEDMS: 1661961600000

      - name: Public result to github
        uses: x-actions/git-push@v1
        continue-on-error: true
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: registry.k8s.io
          PUBLISH_DIR: 'gcr.io'
