name: sync

on:
  schedule:
    - cron: '* 22 * * *'
  push:
      branches:
        - main

jobs:
  coredns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v2
        with:
          repository: x-mirrors/gcr.io
          ref: 'coredns'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@v1
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/coredns.txt"
          DEST_REPO: "docker.io/gcmirrors"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xianbinxie"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"

      - name: Public result to github
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: 'coredns'
          PUBLISH_DIR: 'gcr.io'

  google-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v2
        with:
          repository: x-mirrors/gcr.io
          ref: 'google-samples'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@v1
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/google-samples.txt"
          DEST_REPO: "docker.io/gcriogooglesamples"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xianbinxie"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"

      - name: Public result to github
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: 'google-samples'
          PUBLISH_DIR: 'gcr.io'

  k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v2
        with:
          repository: x-mirrors/gcr.io
          ref: 'k8s'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@v1
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/k8s.txt"
          DEST_REPO: "docker.io/gcmirrors"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xianbinxie"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"
          LOG_LEVEL: "INFO"

      - name: Public result to github
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: 'k8s'
          PUBLISH_DIR: 'gcr.io'

  ml-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v2
        with:
          repository: x-mirrors/gcr.io
          ref: 'ml-pipeline'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@v1
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/ml-pipeline.txt"
          DEST_REPO: "docker.io/gcriomlpipeline"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xianbinxie"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"

      - name: Public result to github
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: ml-pipeline
          PUBLISH_DIR: 'gcr.io'

  scheduler-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout result branch
        uses: actions/checkout@v2
        with:
          repository: x-mirrors/gcr.io
          ref: 'scheduler-plugins'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gcr.io

      - name: Container Images Sync
        uses: x-actions/python3-cisctl@v1
        env:
          GIT_ORG: "x-mirrors"
          GIT_REPO: "gcr.io"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_IMAGE_LIST_URL: "https://raw.githubusercontent.com/x-mirrors/gcr.io/main/scheduler-plugins.txt"
          DEST_REPO: "docker.io/k8sgcrioschedulerplugins"
          SRC_TRANSPORT: "docker"
          DEST_TRANSPORT: "docker"
          DEST_TRANSPORT_USER: "xianbinxie"
          DEST_TRANSPORT_PASSWORD: "${{ secrets.DEST_TRANSPORT_PASSWORD }}"

      - name: Public result to github
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: 'me@xiexianbin.cn'
          GITHUB_USERNAME: 'xiexianbin'
          PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/x-mirrors/gcr.io.git
          PUBLISH_BRANCH: scheduler-plugins
          PUBLISH_DIR: 'gcr.io'
